# (Turtle: draw four squares) Write a program that draws four squares in the center
# of the screen, as shown in Figure 1.18a.
import turtle
# wn = turtle.Screen()
turdle = turtle.Turtle()
turdle.forward(90)
turdle.right(90)
turdle.forward(90)
turdle.right(90)
turdle.forward(180)
turdle.right(90)
turdle.forward(180)
turdle.right(90)
turdle.forward(180)
turdle.right(90)
turdle.forward(90)
turdle.right(90)
turdle.forward(180)
turdle.penup()
turdle.back(90)
turdle.left(90)
turdle.down()
turdle.forward(90)
turdle.penup()
turdle.back(180)
turdle.down()
turdle.forward(90)
turtle.done()