#(Turtle: draw the Olympic symbol ) Write a program that prompts the user to
#enter the radius of the rings and draws an Olympic symbol of five rings of the
#same size with the colors blue, black, red, yellow, and green, as shown in
#Figure 3.5c.

import turtle


radius = eval(input("Enter the radius: "))
t = turtle.Turtle()
t.speed(100)
x = t.xcor()
t.penup()
t.goto(0, 0)
t.backward(radius * 2.5)
t.pendown()
t.pensize(15)
t.color("blue")
t.circle(radius)
t.penup()
t.forward(x + radius * 2.5)
t.pendown()
t.color("black")
t.circle(radius)
t.penup()
t.forward(x + radius * 2.5)
t.pendown()
t.color("red")
t.circle(radius)
t.penup()
t.backward(x + radius * 4.75)
t.left(-90)
t.forward(x + 20)
t.pendown()
t.color("yellow")
t.circle(radius)
t.penup()
t.left(90)
t.forward(x + radius * 2.5)
t.left(-90)
t.forward(x)
t.pendown()
t.color("green")
t.circle(radius)
turtle.done()
